# azure-pipelines.yml
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.7'

steps:
- task: HashiCorpToolInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: $(TF_VERSION)

# Init (uses the service connection for Azure auth)
- task: TerraformCLI@1
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'azure-connection'   # <-- REPLACE with your Service Connection name

# Plan
- task: TerraformCLI@1
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'azure-connection'   # <-- REPLACE
    # If you need to pass vars from Pipeline variables or a Variable Group, use -var options in additionalArguments
    additionalArguments: '-var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var="client_id=$(AZURE_CLIENT_ID)" -var="client_secret=$(AZURE_CLIENT_SECRET)" -var="tenant_id=$(AZURE_TENANT_ID)"'

# Apply (auto-approve)
- task: TerraformCLI@1
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'azure-connection'   # <-- REPLACE
    commandOptions: '-auto-approve'
    additionalArguments: '-var="subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var="client_id=$(AZURE_CLIENT_ID)" -var="client_secret=$(AZURE_CLIENT_SECRET)" -var="tenant_id=$(AZURE_TENANT_ID)"'
