name: Terraform Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
          -var "client_id=$ARM_CLIENT_ID" \
          -var "client_secret=$ARM_CLIENT_SECRET" \
          -var "tenant_id=$ARM_TENANT_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
          -var "client_id=$ARM_CLIENT_ID" \
          -var "client_secret=$ARM_CLIENT_SECRET" \
          -var "tenant_id=$ARM_TENANT_ID"